name: sme_digital
description: SME Digital Platform - Mobile App for small and medium enterprises.
version: 1.0.2+4
publish_to: none

environment:
  sdk: "^3.7.0"

dependencies:
  sentry_flutter: ^9.14.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Navigation
  go_router: ^17.1.0

  # Networking
  dio: ^5.8.0
  retrofit: ^4.4.2

  # Local storage & offline sync
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.4
  shared_preferences: ^2.3.5
  hive_flutter: ^1.1.0

  # Authentication & security
  flutter_secure_storage: ^10.0.0
  local_auth: ^3.0.0

  # UI & UX
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^1.1.1

  # Forms & validation
  reactive_forms: ^18.2.2

  # Utilities
  intl: ^0.20.2
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  logger: ^2.5.0
  connectivity_plus: ^7.0.0
  pdf: ^3.11.1
  printing: ^5.14.2
  share_plus: ^11.1.0
  nepali_utils: ^3.0.8

dev_dependencies:
  sentry_dart_plugin: ^3.2.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # Code generation
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.1

flutter_launcher_icons:
  image_path: assets/icons/app_logo.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: sme-mobile
  org: lax-4w
